# Generated by Django 5.0.1 on 2024-02-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('0', 'female')], max_length=1),
        ),
    ]
