# Generated by Django 5.0.1 on 2024-02-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrdapp', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
